
disabled_rules:
  - variable_name

excluded:
  - Carthage
  - Pods
  - HduIn/Libraries/LeanCloudFeedback
  - HduIn/Controllers/Common/ImageCropperController.swift
  - HduIn/Extension/ExDate.swift
  - HduIn/Libraries/Hue

included:
  - HduIn
  - HduInTests

file_length:
  warning: 900
  error: 1200
function_body_length:
  warning: 120
  error: 200
type_name:
  excluded:
    - PE
variable_name:
  excluded:
    - id
    - to
