#source 'https://git.coding.net/hging/Specs.git'

platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0.1'
        end
    end
end

target 'HduIn' do

    # Basics
    pod 'RealmSwift'
    pod 'XCGLogger', '~> 4.0.0'
    pod 'UITableView+FDTemplateLayoutCell'

    # Networking
    pod 'Moya/RxSwift', '8.0.0-beta.4'
    pod 'ObjectMapper', '~> 2.2'
    pod 'SwiftyJSON'
    pod 'RxCocoa'
    pod 'RxSwift'
    
    # LeanCloud SDK
    pod 'AVOSCloud', '~>3.7.1'
    pod 'AVOSCloudCrashReporting'

    # Utilities
    pod 'InAppSettingsKit', '~>2.8'
    pod 'YYWebImage', '~>1.0.0'
    pod 'YYImage', '~>1.0.0'
    pod 'YYCache', '~>1.0.0'
    pod 'Timepiece', '~>1.0.0'
    pod 'AFImageHelper','~>3.2.1'

    # UI Libraries
    pod 'SnapKit', '~> 3.0.2'
    pod 'TOCropViewController'
    pod 'Static', '~>2.0.1'
    pod 'DateTimePicker'
    pod 'MJRefresh', '~>3.1.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'DKChainableAnimationKit','~>2.0.0'
    pod 'XHWaterfallFlowLayout', '~> 1.0.0'
    #pod 'Reveal-SDK', :configurations => ['Debug']
    pod "Qiniu", "~> 7.1"
    
end

